build:
  test:
    image: qnib/golang
    commands:
      - go get -d
      - go get github.com/stretchr/testify/assert
      - go build
      - go test -cover -coverprofile=main.out
      - go test -cover -coverprofile=lib.out ./lib/
      - coveraggregator -o all.out main.out lib.out

publish:
  coverage:
    server: http://wins.ddns.net:8008
    token: $$GITHUB_API_KEY
    include: .+\\.all.out$
publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: cp2017/go-test
