build:
  test:
    image: qnib/golang
    commands:
      - go get -d
      - go get github.com/stretchr/testify/assert
      - go build
      - go test -cover -coverprofile=main.cover
      - go test -cover -coverprofile=lib.cover ./lib/
      - coveraggregator -o coverage.out main.cover lib.cover

publish:
  coverage:
    server: http://wins.ddns.net:8008
    token: $$GITHUB_API_KEY
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: cp2017/go-test
